version: '3.8'
services:
  test_db:
    image: postgres:16
    container_name: test_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: