version: "3.8"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ClubLinkDeveloper
      POSTGRES_PASSWORD: ClubLinkDeveloperDatabasePassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - type: bind
        source: ./infra/db/seed.sql
        target: /docker-entrypoint-initdb.d/seed.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ClubLinkDeveloper -d mydatabase"]
      interval: 10s
      retries: 5
      timeout: 5s

  backend:
    build:
      context: ../backend
    container_name: test_backend
    ports:
      - "3001:3001"
    depends_on:
      postgres:
        condition: service_healthy
