version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: local_postgres
    restart: always
    environment:
      POSTGRES_USER: ClubLinkDeveloper
      POSTGRES_PASSWORD: ClubLinkDeveloperDatabasePassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
