AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation template for RDS PostgreSQL in Free Tier.

Resources:
  RDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: !Ref DBInstanceIdentifier
      AllocatedStorage: !Ref AllocatedStorage
      DBInstanceClass: db.t4g.micro
      Engine: postgres
      EngineVersion: 16.3
      MasterUsername: !Ref MasterUsername
      MasterUserPassword: "{{resolve:ssm-secure:/dev/postgres/db-password}}"
      BackupRetentionPeriod: 0
      DBName: !Ref DBName
      PubliclyAccessible: false
      VPCSecurityGroups:
        - !Ref VPCSecurityGroup
    DeletionPolicy: Delete

Outputs:
  DatabaseEndpoint:
    Description: Endpoint of the PostgreSQL database.
    Value: !GetAtt RDSInstance.Endpoint.Address
  DatabasePort:
    Description: Port of the PostgreSQL database.
    Value: !GetAtt RDSInstance.Endpoint.Port