AWSTemplateFormatVersion: "2010-09-09"
Description: Combined CloudFormation template for RDS PostgreSQL and S3 bucket.

Parameters:
  DBInstanceIdentifier:
    Type: String
    Default: dev-postgres-db
    Description: Database instance identifier.
  DBName:
    Type: String
    Default: mydatabase
    Description: Name of the database.
  MasterUsername:
    Type: String
    Default: ClubLinkDeveloper
    Description: Master username for the database.
  AllocatedStorage:
    Type: Number
    Default: 5
    Description: Database storage size (in GB).
  VPCSecurityGroup:
    Type: AWS::EC2::SecurityGroup::Id
    Description: Security group for database access.
  Environment:
    Type: String
    Default: dev
    Description: Environment name (e.g., dev, staging, production).
  EC2InstanceType:
    Type: String
    Default: t4g.nano
    Description: EC2 Instance Type
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: The name of the key pair to use for SSH access to the instance.
  BackendSecurityGroup:
    Type: AWS::EC2::SecurityGroup::Id
    Description: Security group for the backend EC2 instance.

Resources:
  RDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: !Ref DBInstanceIdentifier
      AllocatedStorage: !Ref AllocatedStorage
      DBInstanceClass: db.t4g.micro
      Engine: postgres
      EngineVersion: 16.3
      MasterUsername: !Ref MasterUsername
      MasterUserPassword: "{{resolve:ssm-secure:/dev/postgres/db-password}}"
      BackupRetentionPeriod: 0
      DBName: !Ref DBName
      PubliclyAccessible: false
      VPCSecurityGroups:
        - !Ref VPCSecurityGroup
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete

  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "club-images-${Environment}"
      VersioningConfiguration:
        Status: Enabled
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain

  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Deny
            Principal: "*"
            Action: "s3:*"
            Resource:
              - !Sub "arn:aws:s3:::club-images-${Environment}/*"
              - !Sub "arn:aws:s3:::club-images-${Environment}"

  BackendInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref EC2InstanceType
      KeyName: !Ref KeyName
      SecurityGroupIds:
        - !Ref BackendSecurityGroup
      ImageId: ami-01816d07b1128cd2d
      NetworkInterfaces:
        - AssociatePublicIpAddress: false
          SubnetId: subnet-0859e630d3192e8a5
          DeviceIndex: 0
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete

Outputs:
  DatabaseEndpoint:
    Description: Database endpoint
    Value: !GetAtt RDSInstance.Endpoint.Address
  DatabasePort:
    Description: Database port
    Value: !GetAtt RDSInstance.Endpoint.Port
  S3BucketName:
    Description: S3 bucket name
    Value: !Ref S3Bucket
  BackendInstancePrivateIP:
    Description: Private IP address of the backend instance
    Value: !GetAtt BackendInstance.PrivateIp