name: Deploy CloudFormation Template

on:
  push:
    branches:
      - main
    paths:
        - 'infra/**/*.yaml'

jobs:
  deploy:
    name: Deploy CloudFormation Stack
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS CLI
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
        run: aws configure set default.region us-east-1

      - name: Validate CloudFormation Template
        run: aws cloudformation validate-template --template-body file://infra/environments/dev/template.yaml

      - name: Deploy CloudFormation Stack
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
        run: |
          aws cloudformation deploy \
            --stack-name dev-environment \
            --template-file infra/environments/dev/template.yaml \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides file://infra/environments/dev/parameters.json

      - name: Confirm Stack Deployment
        run: aws cloudformation describe-stacks --stack-name dev-environment