name: CloudFormation Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy CloudFormation Template
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS CLI
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
        run: aws --version

      - name: Deploy CloudFormation Stack
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
        run: |
          aws cloudformation deploy \
          --template-file infra/environments/dev/rds-postgres-stack.yaml \
          --stack-name dev-environment \
          --capabilities CAPABILITY_NAMED_IAM \
          --role-arn arn:aws:iam::384708821502:role/AWSCloudFormationExecutionRole