name: Run e2e Tests

on:
  push:
    branches:
      - main
    paths:
      - "frontend/**"
      - "backend/**"
  pull_request:
    branches:
      - main
    paths:
      - "frontend/**"
      - "backend/**"

jobs:
  runs-e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Install Dependencies
        run: |
          npm install
          npm install --prefix frontend
          npm install --prefix backend
          npm install --prefix cypress

      - name: Start Docker Containers
        run: npm run up

      - name: Wait for App to Start
        env:
          REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
          REACT_APP_PUBLISH_KEY: ${{ secrets.REACT_APP_PUBLISH_KEY }}
        run: |
          npm run dev
          npx wait-on http://localhost:3000 --timeout 120000

      - name: Run e2e Tests
        run: npm run e2e
