name: Run e2e Tests

on: [push]

jobs:
  runs-e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Install Dependencies
        run: |
          npm install & \
          npm install --prefix frontend & \
          npm install --prefix backend & \
          wait

      - name: Start Docker Containers
        id: start-docker
        continue-on-error: true
        env:
          REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
          REACT_APP_PUBLISH_KEY: ${{ secrets.REACT_APP_PUBLISH_KEY }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          FRONTEND_URL: ${{ secrets.FRONTEND_URL }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          PORT: ${{ secrets.PORT }}
          PUBLISH_KEY: ${{ secrets.PUBLISH_KEY }}
          RDS_DATABASE: ${{ secrets.RDS_DATABASE }}
          RDS_HOSTNAME: ${{ secrets.RDS_HOSTNAME }}
          RDS_PASSWORD: ${{ secrets.RDS_PASSWORD }}
          RDS_PORT: ${{ secrets.RDS_PORT }}
          RDS_USERNAME: ${{ secrets.RDS_USERNAME }}
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
          STRIPE_WEBHOOK_SECRET: ${{ secrets.STRIPE_WEBHOOK_SECRET }}
        run: |
          docker-compose -f ./infra/docker-compose.test.yml up -d
          sleep 5
          docker ps -a

      - name: Wait for PostgreSQL to be ready
        run: |
          until docker exec infra-postgres-1 pg_isready -U ${{ secrets.RDS_USERNAME }} -d ${{ secrets.RDS_DATABASE }}; do
            echo "Waiting for database..."
            sleep 5
          done
          echo "Database is ready!"

      - name: Start Frontend
        run: |
          npm run start --prefix frontend &
          sleep 5

      - name: Wait for Frontend to Start
        run: |
          npx wait-on http://localhost:3000 --timeout 120000

      - name: Run e2e Tests
        run: npm run e2e
