name: Lint

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'infra/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'infra/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint Codebase
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Dependencies
        run: |
          npm install
      
      - name: Lint
        run: npm run lint