name: Run Tests

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - 'backend/**'
  pull_request:
    branches:
      - main
    paths:
      - 'frontend/**'
      - 'backend/**'
  
jobs:
  unit-tests-backend:
    runs-on: ubuntu-latest
    name: Backend Unit Tests

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Backend Dependencies
        working-directory: ./backend
        run: npm install

      - name: Run Backend Unit Tests
        working-directory: ./backend
        run: npm run test:unit
  
  integration-tests-backend:
    runs-on: ubuntu-latest
    name: Backend Integration Tests

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
      - name: Ensure .env.test Exists
        run: |
          cat > .env.test <<EOF
          POSTGRES_USER=test_user
          POSTGRES_PASSWORD=test_password
          POSTGRES_DB=test_db
          POSTGRES_HOST=localhost
          EOF
        working-directory: ./backend

      - name: Install Backend Dependencies
        working-directory: ./backend
        run: npm install
      
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Setup Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d
        working-directory: ./backend
      
      - name: Wait for Services to Be Ready
        run: |
          until docker-compose -f docker-compose.yml exec -T test_db pg_isready -U test_user -d test_db --timeout=0; do
            echo "Waiting for database..."
            sleep 5
          done
        working-directory: ./backend

      - name: Run Backend Integration Tests
        run: npm run test:integration
        working-directory: ./backend
      
      - name: Tear Down Docker Compose
        if: always()
        run: docker-compose -f docker-compose.yml down
        working-directory: ./backend

  frontend-tests:
    runs-on: ubuntu-latest
    name: Frontend Tests

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Deps
        run: npm install

      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: npm install

      - name: Install Playwright Dependencies
        run: npx playwright install-deps
      
      - name: Install Playwright Browsers
        run: npx playwright install

      - name: Run Frontend Tests
        run: npx playwright test tests/frontend/**