name: Run Tests

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - 'backend/**'
  pull_request:
    branches:
      - main
    paths:
      - 'frontend/**'
      - 'backend/**'
  
jobs:
  unit-tests-backend:
    runs-on: ubuntu-latest
    name: Backend Unit Tests

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Backend Dependencies
        working-directory: ./backend
        run: npm install

      - name: Run Backend Unit Tests
        working-directory: ./backend
        run: npm run test:unit
  
  integration-tests-backend:
    runs-on: ubuntu-latest
    name: Backend Integration Tests

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Backend Dependencies
        working-directory: ./backend
        run: npm install

      - name: Run Backend Integration Tests
        run: npm run test:integration
        working-directory: ./backend

  frontend-tests:
    runs-on: ubuntu-latest
    name: Frontend Tests

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Deps
        run: npm install

      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: npm install

      - name: Install Playwright Dependencies
        run: npx playwright install-deps
      
      - name: Install Playwright Browsers
        run: npx playwright install

      - name: Run Frontend Tests
        run: npx playwright test tests/frontend/**