name: Run Tests

on:
  push:
    branches:
      - main
    paths:
      - "frontend/**"
      - "backend/**"
  pull_request:
    branches:
      - main
    paths:
      - "frontend/**"
      - "backend/**"

jobs:
  unit-tests-backend:
    runs-on: ubuntu-latest
    name: Backend Unit Tests

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "npm"

      - name: Install Backend Dependencies
        working-directory: ./backend
        run: npm install

      - name: Run Backend Unit Tests
        working-directory: ./backend
        run: npm run test:unit

  integration-tests-backend:
    runs-on: ubuntu-latest
    name: Backend Integration Tests

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "npm"

      - name: Install Backend Dependencies
        working-directory: ./backend
        run: npm install

      - name: Run Backend Integration Tests
        run: npm run test:integration
        working-directory: ./backend

  unit-tests-frontend:
    runs-on: ubuntu-latest
    name: Frontend Unit Tests

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "npm"

      - name: Install Deps
        run: npm install
        working-directory: ./frontend

      - name: Run Frontend Unit Tests
        run: npm run test:unit
        working-directory: ./frontend

  integration-tests-frontend:
    runs-on: ubuntu-latest
    name: Frontend Integration Tests

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"

      - name: Install Deps
        run: npm install
        working-directory: ./frontend

      - name: Run Frontend Integration Tests
        run: npm run test:integration
        working-directory: ./frontend
